title: Xinyi(Cindy) Wang # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   I’m currently learning math-computer science && cognitive science with specialization on machine learning and neural computation in UC San Diego 
  <br><br>
  It is my hope to one day work in the area of computer science and artificial intelligence. I am intrigued and fascinated by the seemingly unlimited potential of these areas of study and development to improve the quality of life. It is my desire to learn as much as possible about all areas of computer science and the development of artificial intelligence to build a strong foundation for pursuing a career in computer science and mathematics. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
