title: Xinyi(Cindy) Wang # your name (or website title) here
logo: "logo.pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I’m currently a thrid year student at UC San Diego double majoring in
  <b>math-computer science</b> && <b>cognitive science</b> with specialization on machine learning and neural computation
  <br><br>
  <b>My Email</b>: xiw013@ucsd.edu
  <br><br>
  <a href="https://www.linkedin.com/in/xinyi-cindy-wang-47ab3421b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
