title: Xinyi(Cindy) Wang # your name (or website title) here
logo: "logo.pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a thrid year student at UC San Diego majoring in
  <b>math-computer science</b> && <b>cognitive science</b>.
  <br>
  My Email: xiw013@ucsd.edu 
  <br>
  My Phone Number: 949-885-6251
  <br><br>
  <a href="https://www.linkedin.com/in/xinyi-cindy-wang-47ab3421b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
