title: Xinyi(Cindy) Wang # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I’m currently a thrid year student at UC San Diego double majoring in
  math-computer science && cognitive science with specialization on machine learning and neural computation
  <br><br>
  <a href="https://www.linkedin.com/in/xinyi-cindy-wang-47ab3421b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
